version: '3.4'
services:
  # web:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   volumes:
  #          - ".:/home/www/messenger-task-scheduler-bot"
  #   ports:
  #     - "80:3000"
    # depends_on:
      # - mongo
    # restart: always
  postgres:
    image: postgres:10.2
    environment:
      POSTGRES_USER: firstCFBot
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: first_cf_bot_dev
      PGDATA: /data/postgres
    volumes:
       - /home/dev26/projects/postgresDataFirstCFBot:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    # restart: unless-stopped
  
  pgadmin:
    links:
      - postgres:postgres
    image: fenglc/pgadmin4
    volumes:
       - /home/dev26/projects/pgadmin:/root/.pgadmin
    ports:
      - "5050:5050"
    networks:
      - postgres
    # restart: unless-stopped
  
  redis:
    image: redis:4
    ports: 
      - "6379:6379"
    networks:
      - postgres
    
networks:
  postgres:
    driver: bridge
