version: '3.4'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
           - ".:/home/www/messenger-task-scheduler-bot"
    ports:
      - "80:3000"
    # depends_on:
      # - mongo
    # restart: always
  # mongo:
  #   command: mongod
  #   image: mongo:3-jessie
    # ports:
      # - "27100:27017" # map port to none standard port, to avoid conflicts with locally installed mongodb.

    # Прив'язка VOLUME із MongoImage за допомогою
    # docker-compose volumes до файлової системи хосту.
    # https://docs.docker.com/compose/compose-file/#volumes
    # https://docs.docker.com/engine/reference/builder/#volume
    # https://docs.docker.com/engine/admin/volumes/volumes/
    # volumes:
    #   - ./../database/mongo/db:/data/db
    #   - ./../database/mongo/configDb:/data/configdb
    # restart: always
